#!/bin/sh

d=`pwd`

ide_dir=`dirname "$0"`
cd "$ide_dir"
ide_dir=`pwd`
 
cd $d
cat `cat build` | "$ide_dir/convert_bas.py" | petcat -w2 -o prog
c1541 -format tmp,00 d64 tmp.d64 -write prog
rm prog
x64 +sound -warp -virtualdev -8 tmp.d64 "$ide_dir/basic-boss.vsf"
